openapi: "3.0.2"

info:
  title: "todo-api"
  description: "A RESTful API for task management."
  version: "1.0"
  contact:
    name: "GitHub"
    url: "https://github.com/muhammadh-s/todo-api"


servers:
- url: "https://todo-flask-restful-api.herokuapp.com/"

paths:
  /todos:
    get:
      tags:
      - todos
      summary: "Calls a list of todos"
      description: ""
      operationId: note

      responses:
        200:
          description: Successful response


security:
- app_id: []

tags:
  - name: Notes
    description: ""
